version: '3.4'

services:
  be-customerstore:
    build:
      context: .
      dockerfile: BE-CustomerStore/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8081:80"